---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add ThreatStack apt key
  apt_key:
    url: '{{ threatstack_gpg_key_yrl }}'
    id: '{{ threatstack_gpg_key_id }}'
    state: present

- name: Add ThreatStack apt repo
  apt_repository:
    repo: 'deb {{ threatstack_repo_url }} {{ ansible_distribution_release }} main'
    filename: '{{ threatstack_repo_file }}'
    state: present
    update_cache: yes

- name: Install ThreatStack client
  apt:
    name: '{{ threatstack_package }}'
    state: latest
  register: installation

- name: 'Reload systemd services'
  systemd:
    daemon_reload: true
  when: installation.changed

- name: 'Verify {{ threatstack_service }} service is stopped'
  systemd:
    name: '{{ threatstack_service }}'
    state: stopped

- name: 'Initial {{ threatstack_service }} service setup' 
  command: >
    tsagent setup \
      --deploy-key="{{ threatstack_deploy_key }}" \
      {% for rule_set in threatstack_rule_sets %}
      --ruleset="{{ rule_set }}" 
      {% endfor %}
  when: installation.changed

- name: 'Configure: {{ item.k }}={{ item.v }}'
  command: >
    tsagent config -set {{ item.k }} {{ item.v }}
  with_items: '{{ threatstack_config }}'

- name: 'Verify {{ threatstack_service }} service is started'
  systemd:
    name: '{{ threatstack_service }}'
    state: started
    enabled: true
    masked: false
